// Hand-curated TechGraph seed dataset.
// Every relationship is a true real-world statement (see docs/DATA_MODEL.md,
// modeling principle 2). Company HIRES_FOR edges are realistic demo data,
// not claims about current openings.
//
// Totals: 76 nodes (16 Skill, 21 Technology, 14 Concept, 8 Job, 8 Company,
// 9 Course) and 185 relationships.

export const skills = [
  { name: 'Python', category: 'language', difficulty: 'beginner', description: 'General-purpose programming language; the default choice for data, ML and automation work.' },
  { name: 'JavaScript', category: 'language', difficulty: 'beginner', description: 'The language of the web; runs in every browser and on servers via Node.js.' },
  { name: 'TypeScript', category: 'language', difficulty: 'intermediate', description: 'Statically-typed superset of JavaScript for large, maintainable codebases.' },
  { name: 'HTML & CSS', category: 'language', difficulty: 'beginner', description: 'The structure and styling of every web page.' },
  { name: 'SQL', category: 'data', difficulty: 'beginner', description: 'Querying and transforming data in relational databases.' },
  { name: 'Git', category: 'practice', difficulty: 'beginner', description: 'Version control: branching, merging and collaborating on code.' },
  { name: 'Linux', category: 'practice', difficulty: 'beginner', description: 'Working on the command line: shells, processes, permissions, servers.' },
  { name: 'Statistics', category: 'data', difficulty: 'intermediate', description: 'Probability, distributions and hypothesis testing — the math behind data science.' },
  { name: 'Data Analysis', category: 'data', difficulty: 'intermediate', description: 'Exploring, cleaning and interpreting datasets to answer real questions.' },
  { name: 'Data Modeling', category: 'data', difficulty: 'intermediate', description: 'Designing schemas and structures that represent a domain faithfully.' },
  { name: 'Machine Learning', category: 'domain', difficulty: 'advanced', description: 'Designing, training and evaluating models that learn patterns from data.' },
  { name: 'API Design', category: 'practice', difficulty: 'intermediate', description: 'Designing clear, consistent interfaces between services and their clients.' },
  { name: 'Testing', category: 'practice', difficulty: 'intermediate', description: 'Writing automated tests that keep software changeable with confidence.' },
  { name: 'CI/CD', category: 'practice', difficulty: 'intermediate', description: 'Automating build, test and deployment pipelines.' },
  { name: 'Cloud Fundamentals', category: 'domain', difficulty: 'intermediate', description: 'Core cloud concepts: compute, storage, networking and managed services.' },
  { name: 'Infrastructure as Code', category: 'practice', difficulty: 'advanced', description: 'Declaring and versioning infrastructure the way you version application code.' },
];

export const technologies = [
  { name: 'PyTorch', type: 'framework', description: 'Open-source deep learning framework with a Python-first API.' },
  { name: 'TensorFlow', type: 'framework', description: 'End-to-end deep learning platform, from research to production deployment.' },
  { name: 'scikit-learn', type: 'library', description: 'The standard Python toolkit for classical machine learning.' },
  { name: 'NumPy', type: 'library', description: 'The fundamental package for numerical computing in Python.' },
  { name: 'pandas', type: 'library', description: 'DataFrames for cleaning, transforming and analyzing tabular data in Python.' },
  { name: 'Jupyter', type: 'tool', description: 'Interactive notebooks for exploratory data work and sharing results.' },
  { name: 'Hugging Face Transformers', type: 'library', description: 'Pretrained transformer models for text, vision and audio tasks.' },
  { name: 'React', type: 'framework', description: 'The most widely used library for building component-based user interfaces.' },
  { name: 'Next.js', type: 'framework', description: 'React framework adding routing, rendering strategies and full-stack features.' },
  { name: 'Vite', type: 'tool', description: 'Fast dev server and build tool for modern frontend projects.' },
  { name: 'Tailwind CSS', type: 'framework', description: 'Utility-first CSS framework for building designs directly in markup.' },
  { name: 'Node.js', type: 'platform', description: 'JavaScript runtime for building servers and tooling outside the browser.' },
  { name: 'Express.js', type: 'framework', description: 'Minimal, unopinionated web framework for Node.js APIs.' },
  { name: 'PostgreSQL', type: 'database', description: 'Advanced open-source relational database.' },
  { name: 'MongoDB', type: 'database', description: 'Document database storing flexible JSON-like records.' },
  { name: 'Redis', type: 'database', description: 'In-memory data store used for caching, queues and fast lookups.' },
  { name: 'Docker', type: 'tool', description: 'Packaging applications and their dependencies into portable containers.' },
  { name: 'Kubernetes', type: 'platform', description: 'Orchestrating, scaling and healing containerized workloads.' },
  { name: 'AWS', type: 'platform', description: "Amazon's cloud platform: compute, storage and hundreds of managed services." },
  { name: 'Apache Spark', type: 'framework', description: 'Distributed engine for processing large datasets in parallel.' },
  { name: 'Apache Airflow', type: 'tool', description: 'Programmatically authoring and scheduling data pipelines as DAGs.' },
];

export const concepts = [
  { name: 'Deep Learning', field: 'AI/ML', description: 'Multi-layer neural networks; the engine behind modern AI systems.' },
  { name: 'Natural Language Processing', field: 'AI/ML', description: 'Teaching machines to understand and generate human language.' },
  { name: 'Computer Vision', field: 'AI/ML', description: 'Extracting meaning from images and video.' },
  { name: 'Predictive Modeling', field: 'AI/ML', description: 'Using historical data to forecast outcomes and classify cases.' },
  { name: 'Numerical Computing', field: 'data', description: 'Efficient computation over large arrays and matrices.' },
  { name: 'Data Wrangling', field: 'data', description: 'Getting messy real-world data into a usable shape.' },
  { name: 'Data Pipelines', field: 'data', description: 'Moving and transforming data reliably between systems on a schedule.' },
  { name: 'REST APIs', field: 'web', description: 'Exposing application functionality over predictable HTTP interfaces.' },
  { name: 'Single-Page Applications', field: 'web', description: 'Web apps that render and route in the browser for an app-like feel.' },
  { name: 'Responsive Design', field: 'web', description: 'Interfaces that adapt gracefully to any screen size.' },
  { name: 'Containerization', field: 'infrastructure', description: 'Isolating software in lightweight, reproducible runtime units.' },
  { name: 'Data Persistence', field: 'infrastructure', description: 'Storing state durably and retrieving it efficiently.' },
  { name: 'Caching', field: 'infrastructure', description: 'Keeping hot data close to reduce latency and load.' },
  { name: 'Cloud Infrastructure', field: 'infrastructure', description: 'Running systems on elastic, managed cloud resources.' },
];

export const jobs = [
  { name: 'ML Engineer', level: 'mid', avgSalaryUSD: 145000, description: 'Builds, trains and ships machine-learning systems to production.' },
  { name: 'NLP Engineer', level: 'senior', avgSalaryUSD: 160000, description: 'Builds language-model applications: search, chatbots, text analytics.' },
  { name: 'Data Scientist', level: 'mid', avgSalaryUSD: 130000, description: 'Turns raw data into insight with statistics and predictive models.' },
  { name: 'Data Engineer', level: 'mid', avgSalaryUSD: 128000, description: 'Designs and operates the pipelines and warehouses data teams rely on.' },
  { name: 'Frontend Developer', level: 'junior', avgSalaryUSD: 95000, description: 'Builds the interfaces users see and touch in the browser.' },
  { name: 'Backend Developer', level: 'mid', avgSalaryUSD: 115000, description: 'Designs the APIs, services and data layers behind applications.' },
  { name: 'Full-Stack Developer', level: 'mid', avgSalaryUSD: 120000, description: 'Works across the stack, from database to browser.' },
  { name: 'DevOps Engineer', level: 'mid', avgSalaryUSD: 135000, description: 'Automates infrastructure, deployment and reliability of production systems.' },
];

export const companies = [
  { name: 'Google', industry: 'Technology', description: 'Search, cloud and AI products at global scale.' },
  { name: 'Microsoft', industry: 'Technology', description: 'Platforms and productivity: Azure, Windows, GitHub and AI.' },
  { name: 'Amazon', industry: 'E-commerce & Cloud', description: 'Global e-commerce and AWS, the largest cloud provider.' },
  { name: 'NVIDIA', industry: 'Semiconductors', description: 'GPUs and software powering the deep-learning boom.' },
  { name: 'Netflix', industry: 'Media & Streaming', description: 'Streaming entertainment driven by data and personalization.' },
  { name: 'Spotify', industry: 'Media & Streaming', description: 'Audio streaming with heavy investment in recommendation systems.' },
  { name: 'Shopify', industry: 'E-commerce', description: 'Commerce platform powering millions of online stores.' },
  { name: 'Airbnb', industry: 'Travel', description: 'Marketplace for stays and experiences, known for strong design and data culture.' },
];

export const courses = [
  { name: 'Python for Everybody', provider: 'University of Michigan (Coursera)', level: 'beginner', url: 'https://www.coursera.org/specializations/python', description: 'Gentle, famous introduction to programming with Python.' },
  { name: 'The Complete SQL Bootcamp', provider: 'Udemy', level: 'beginner', url: 'https://www.udemy.com/course/the-complete-sql-bootcamp/', description: 'PostgreSQL-based SQL from zero to analysis queries.' },
  { name: 'Machine Learning Specialization', provider: 'DeepLearning.AI & Stanford (Coursera)', level: 'intermediate', url: 'https://www.coursera.org/specializations/machine-learning-introduction', description: "Andrew Ng's modern introduction to supervised and unsupervised learning." },
  { name: 'Deep Learning Specialization', provider: 'DeepLearning.AI (Coursera)', level: 'intermediate', url: 'https://www.coursera.org/specializations/deep-learning', description: 'Five-course series on neural networks, CNNs and sequence models.' },
  { name: 'PyTorch for Deep Learning Bootcamp', provider: 'Udemy', level: 'intermediate', url: 'https://www.udemy.com/course/pytorch-for-deep-learning/', description: 'Hands-on course building neural networks in PyTorch from scratch.' },
  { name: 'The Web Developer Bootcamp', provider: 'Udemy', level: 'beginner', url: 'https://www.udemy.com/course/the-web-developer-bootcamp/', description: 'Full-stack web development from HTML to Node.' },
  { name: 'React - The Complete Guide', provider: 'Udemy', level: 'intermediate', url: 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/', description: 'Deep, project-based React course.' },
  { name: 'Docker & Kubernetes: The Practical Guide', provider: 'Udemy', level: 'intermediate', url: 'https://www.udemy.com/course/docker-kubernetes-the-practical-guide/', description: 'Containers and orchestration from the ground up.' },
  { name: 'Data Engineering Zoomcamp', provider: 'DataTalksClub', level: 'intermediate', url: 'https://github.com/DataTalksClub/data-engineering-zoomcamp', description: 'Free, cohort-based course covering the modern data engineering stack.' },
];

// ---------------------------------------------------------------------------
// Relationships. Shapes: { from, to } — plus { level } on job requirements.
// ---------------------------------------------------------------------------

// (:Skill)-[:LEADS_TO]->(:Skill) — learning progression. 15 edges.
export const leadsTo = [
  { from: 'HTML & CSS', to: 'JavaScript' },
  { from: 'JavaScript', to: 'TypeScript' },
  { from: 'JavaScript', to: 'API Design' },
  { from: 'Python', to: 'Data Analysis' },
  { from: 'Python', to: 'Machine Learning' },
  { from: 'Python', to: 'API Design' },
  { from: 'SQL', to: 'Data Analysis' },
  { from: 'SQL', to: 'Data Modeling' },
  { from: 'Statistics', to: 'Machine Learning' },
  { from: 'Data Analysis', to: 'Machine Learning' },
  { from: 'Git', to: 'CI/CD' },
  { from: 'Testing', to: 'CI/CD' },
  { from: 'CI/CD', to: 'Infrastructure as Code' },
  { from: 'Linux', to: 'Cloud Fundamentals' },
  { from: 'Cloud Fundamentals', to: 'Infrastructure as Code' },
];

// (:Technology)-[:REQUIRES]->(:Skill) — competence prerequisite. 29 edges.
export const techRequires = [
  { from: 'PyTorch', to: 'Python' },
  { from: 'PyTorch', to: 'Machine Learning' },
  { from: 'TensorFlow', to: 'Python' },
  { from: 'TensorFlow', to: 'Machine Learning' },
  { from: 'scikit-learn', to: 'Python' },
  { from: 'scikit-learn', to: 'Statistics' },
  { from: 'NumPy', to: 'Python' },
  { from: 'pandas', to: 'Python' },
  { from: 'Jupyter', to: 'Python' },
  { from: 'Hugging Face Transformers', to: 'Python' },
  { from: 'Hugging Face Transformers', to: 'Machine Learning' },
  { from: 'React', to: 'JavaScript' },
  { from: 'Next.js', to: 'JavaScript' },
  { from: 'Vite', to: 'JavaScript' },
  { from: 'Tailwind CSS', to: 'HTML & CSS' },
  { from: 'Node.js', to: 'JavaScript' },
  { from: 'Express.js', to: 'JavaScript' },
  { from: 'Express.js', to: 'API Design' },
  { from: 'PostgreSQL', to: 'SQL' },
  { from: 'PostgreSQL', to: 'Data Modeling' },
  { from: 'MongoDB', to: 'Data Modeling' },
  { from: 'Redis', to: 'Data Modeling' },
  { from: 'Docker', to: 'Linux' },
  { from: 'Kubernetes', to: 'Linux' },
  { from: 'Kubernetes', to: 'Cloud Fundamentals' },
  { from: 'AWS', to: 'Cloud Fundamentals' },
  { from: 'Apache Spark', to: 'Python' },
  { from: 'Apache Spark', to: 'SQL' },
  { from: 'Apache Airflow', to: 'Python' },
];

// (:Technology)-[:WORKS_WITH]->(:Technology) — stack affinity, symmetric:
// each pair stored once, queries match it undirected. 16 edges.
export const worksWith = [
  { from: 'PyTorch', to: 'NumPy' },
  { from: 'PyTorch', to: 'Hugging Face Transformers' },
  { from: 'TensorFlow', to: 'NumPy' },
  { from: 'pandas', to: 'NumPy' },
  { from: 'pandas', to: 'Jupyter' },
  { from: 'scikit-learn', to: 'pandas' },
  { from: 'React', to: 'Vite' },
  { from: 'React', to: 'Tailwind CSS' },
  { from: 'React', to: 'Next.js' },
  { from: 'Node.js', to: 'Express.js' },
  { from: 'Express.js', to: 'PostgreSQL' },
  { from: 'Express.js', to: 'MongoDB' },
  { from: 'Node.js', to: 'Redis' },
  { from: 'Docker', to: 'Kubernetes' },
  { from: 'Kubernetes', to: 'AWS' },
  { from: 'Apache Airflow', to: 'Apache Spark' },
];

// (:Technology)-[:USED_FOR]->(:Concept) — purpose. 25 edges.
export const usedFor = [
  { from: 'PyTorch', to: 'Deep Learning' },
  { from: 'PyTorch', to: 'Computer Vision' },
  { from: 'TensorFlow', to: 'Deep Learning' },
  { from: 'TensorFlow', to: 'Computer Vision' },
  { from: 'Hugging Face Transformers', to: 'Natural Language Processing' },
  { from: 'Hugging Face Transformers', to: 'Deep Learning' },
  { from: 'scikit-learn', to: 'Predictive Modeling' },
  { from: 'NumPy', to: 'Numerical Computing' },
  { from: 'pandas', to: 'Data Wrangling' },
  { from: 'Jupyter', to: 'Data Wrangling' },
  { from: 'Apache Spark', to: 'Data Pipelines' },
  { from: 'Apache Airflow', to: 'Data Pipelines' },
  { from: 'Express.js', to: 'REST APIs' },
  { from: 'Node.js', to: 'REST APIs' },
  { from: 'React', to: 'Single-Page Applications' },
  { from: 'Next.js', to: 'Single-Page Applications' },
  { from: 'Vite', to: 'Single-Page Applications' },
  { from: 'Tailwind CSS', to: 'Responsive Design' },
  { from: 'Docker', to: 'Containerization' },
  { from: 'Kubernetes', to: 'Containerization' },
  { from: 'AWS', to: 'Cloud Infrastructure' },
  { from: 'PostgreSQL', to: 'Data Persistence' },
  { from: 'MongoDB', to: 'Data Persistence' },
  { from: 'Redis', to: 'Caching' },
  { from: 'Redis', to: 'Data Persistence' },
];

// (:Job)-[:REQUIRES {level}]->(:Skill) — hiring requirement. 33 edges.
export const jobRequires = [
  { from: 'ML Engineer', to: 'Python', level: 'core' },
  { from: 'ML Engineer', to: 'Machine Learning', level: 'core' },
  { from: 'ML Engineer', to: 'SQL', level: 'nice-to-have' },
  { from: 'ML Engineer', to: 'CI/CD', level: 'nice-to-have' },
  { from: 'NLP Engineer', to: 'Python', level: 'core' },
  { from: 'NLP Engineer', to: 'Machine Learning', level: 'core' },
  { from: 'NLP Engineer', to: 'Statistics', level: 'nice-to-have' },
  { from: 'Data Scientist', to: 'Python', level: 'core' },
  { from: 'Data Scientist', to: 'Statistics', level: 'core' },
  { from: 'Data Scientist', to: 'Data Analysis', level: 'core' },
  { from: 'Data Scientist', to: 'SQL', level: 'nice-to-have' },
  { from: 'Data Scientist', to: 'Machine Learning', level: 'nice-to-have' },
  { from: 'Data Engineer', to: 'SQL', level: 'core' },
  { from: 'Data Engineer', to: 'Python', level: 'core' },
  { from: 'Data Engineer', to: 'Data Modeling', level: 'core' },
  { from: 'Data Engineer', to: 'Cloud Fundamentals', level: 'nice-to-have' },
  { from: 'Frontend Developer', to: 'HTML & CSS', level: 'core' },
  { from: 'Frontend Developer', to: 'JavaScript', level: 'core' },
  { from: 'Frontend Developer', to: 'Git', level: 'core' },
  { from: 'Frontend Developer', to: 'TypeScript', level: 'nice-to-have' },
  { from: 'Backend Developer', to: 'JavaScript', level: 'core' },
  { from: 'Backend Developer', to: 'API Design', level: 'core' },
  { from: 'Backend Developer', to: 'SQL', level: 'core' },
  { from: 'Backend Developer', to: 'Testing', level: 'nice-to-have' },
  { from: 'Full-Stack Developer', to: 'JavaScript', level: 'core' },
  { from: 'Full-Stack Developer', to: 'HTML & CSS', level: 'core' },
  { from: 'Full-Stack Developer', to: 'API Design', level: 'core' },
  { from: 'Full-Stack Developer', to: 'SQL', level: 'nice-to-have' },
  { from: 'Full-Stack Developer', to: 'Git', level: 'nice-to-have' },
  { from: 'DevOps Engineer', to: 'Linux', level: 'core' },
  { from: 'DevOps Engineer', to: 'CI/CD', level: 'core' },
  { from: 'DevOps Engineer', to: 'Cloud Fundamentals', level: 'core' },
  { from: 'DevOps Engineer', to: 'Infrastructure as Code', level: 'nice-to-have' },
];

// (:Job)-[:USES]->(:Technology) — the role's day-to-day stack. 28 edges.
export const jobUses = [
  { from: 'ML Engineer', to: 'PyTorch' },
  { from: 'ML Engineer', to: 'scikit-learn' },
  { from: 'ML Engineer', to: 'Docker' },
  { from: 'ML Engineer', to: 'AWS' },
  { from: 'NLP Engineer', to: 'PyTorch' },
  { from: 'NLP Engineer', to: 'Hugging Face Transformers' },
  { from: 'Data Scientist', to: 'pandas' },
  { from: 'Data Scientist', to: 'NumPy' },
  { from: 'Data Scientist', to: 'Jupyter' },
  { from: 'Data Scientist', to: 'scikit-learn' },
  { from: 'Data Engineer', to: 'Apache Spark' },
  { from: 'Data Engineer', to: 'Apache Airflow' },
  { from: 'Data Engineer', to: 'PostgreSQL' },
  { from: 'Data Engineer', to: 'AWS' },
  { from: 'Frontend Developer', to: 'React' },
  { from: 'Frontend Developer', to: 'Vite' },
  { from: 'Frontend Developer', to: 'Tailwind CSS' },
  { from: 'Backend Developer', to: 'Node.js' },
  { from: 'Backend Developer', to: 'Express.js' },
  { from: 'Backend Developer', to: 'PostgreSQL' },
  { from: 'Backend Developer', to: 'Redis' },
  { from: 'Full-Stack Developer', to: 'React' },
  { from: 'Full-Stack Developer', to: 'Node.js' },
  { from: 'Full-Stack Developer', to: 'Express.js' },
  { from: 'Full-Stack Developer', to: 'MongoDB' },
  { from: 'DevOps Engineer', to: 'Docker' },
  { from: 'DevOps Engineer', to: 'Kubernetes' },
  { from: 'DevOps Engineer', to: 'AWS' },
];

// (:Company)-[:HIRES_FOR]->(:Job) — realistic demo data. 21 edges.
export const hiresFor = [
  { from: 'Google', to: 'ML Engineer' },
  { from: 'Google', to: 'Data Scientist' },
  { from: 'Google', to: 'Backend Developer' },
  { from: 'Microsoft', to: 'ML Engineer' },
  { from: 'Microsoft', to: 'Full-Stack Developer' },
  { from: 'Microsoft', to: 'DevOps Engineer' },
  { from: 'Amazon', to: 'Data Engineer' },
  { from: 'Amazon', to: 'DevOps Engineer' },
  { from: 'Amazon', to: 'Backend Developer' },
  { from: 'NVIDIA', to: 'ML Engineer' },
  { from: 'NVIDIA', to: 'NLP Engineer' },
  { from: 'Netflix', to: 'Data Engineer' },
  { from: 'Netflix', to: 'Data Scientist' },
  { from: 'Netflix', to: 'Backend Developer' },
  { from: 'Spotify', to: 'Data Scientist' },
  { from: 'Spotify', to: 'Backend Developer' },
  { from: 'Spotify', to: 'Frontend Developer' },
  { from: 'Shopify', to: 'Frontend Developer' },
  { from: 'Shopify', to: 'Full-Stack Developer' },
  { from: 'Airbnb', to: 'Frontend Developer' },
  { from: 'Airbnb', to: 'Data Scientist' },
];

// (:Course)-[:TEACHES]->(:Skill) — 7 edges.
export const teachesSkill = [
  { from: 'Python for Everybody', to: 'Python' },
  { from: 'The Complete SQL Bootcamp', to: 'SQL' },
  { from: 'Machine Learning Specialization', to: 'Machine Learning' },
  { from: 'Deep Learning Specialization', to: 'Machine Learning' },
  { from: 'PyTorch for Deep Learning Bootcamp', to: 'Machine Learning' },
  { from: 'The Web Developer Bootcamp', to: 'HTML & CSS' },
  { from: 'The Web Developer Bootcamp', to: 'JavaScript' },
];

// (:Course)-[:TEACHES]->(:Technology) — 11 edges.
export const teachesTechnology = [
  { from: 'The Complete SQL Bootcamp', to: 'PostgreSQL' },
  { from: 'Machine Learning Specialization', to: 'scikit-learn' },
  { from: 'Deep Learning Specialization', to: 'TensorFlow' },
  { from: 'PyTorch for Deep Learning Bootcamp', to: 'PyTorch' },
  { from: 'The Web Developer Bootcamp', to: 'Node.js' },
  { from: 'React - The Complete Guide', to: 'React' },
  { from: 'Docker & Kubernetes: The Practical Guide', to: 'Docker' },
  { from: 'Docker & Kubernetes: The Practical Guide', to: 'Kubernetes' },
  { from: 'Data Engineering Zoomcamp', to: 'Apache Spark' },
  { from: 'Data Engineering Zoomcamp', to: 'Apache Airflow' },
  { from: 'Data Engineering Zoomcamp', to: 'Docker' },
];
